name: restaurant_queue_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.3
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.3.4   # เพิ่ม: ทำให้ sqflite ใช้งานได้บน Windows/Linux/macOS (desktop)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true